# Generated by Django 4.2.2 on 2024-05-28 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0005_alter_productimage_product_image_favorite"),
    ]

    operations = [
        migrations.AlterField(
            model_name="favorite",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favorites",
                to="products.products",
            ),
        ),
    ]
