# Generated by Django 4.2.2 on 2024-05-30 12:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("brands", "0001_initial"),
        ("reviews", "0002_alter_productreview_rating"),
        ("inventory", "0002_alter_inventory_options"),
        ("products", "0006_alter_favorite_product"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Products",
            new_name="Product",
        ),
    ]
