# Generated by Django 4.2.2 on 2024-08-19 10:36

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0008_alter_productcategory_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimage",
            name="product_image",
            field=cloudinary.models.CloudinaryField(
                max_length=255, verbose_name="image"
            ),
        ),
    ]
