# Generated by Django 4.2.2 on 2024-07-10 13:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_remove_orderitem_inventory_orderitem_product"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="transaction",
        ),
    ]
