# Generated by Django 4.2.2 on 2024-06-06 18:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_alter_order_transaction_alter_order_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
