# Generated by Django 4.2.2 on 2024-08-19 10:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0006_alter_cartitem_price"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cartitem",
            options={"ordering": ("created_at",)},
        ),
        migrations.AlterModelOptions(
            name="shoppingcart",
            options={"ordering": ("created_at",)},
        ),
    ]
