# Generated by Django 4.2.2 on 2024-06-03 15:21

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('PE', 'Pending'), ('PA', 'Paid'), ('RE', 'Refunded'), ('FA', 'Failed'), ('CA', 'Cancelled')], default='PE', max_length=2)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateTimeField(default=datetime.datetime.now)),
                ('payment_method', models.CharField(choices=[('CA', 'Cash'), ('MO', 'Momo'), ('CD', 'Card'), ('SP', 'St_points'), ('RP', 'Referral_points')], default='CD', max_length=2)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
