# Generated by Django 4.2.2 on 2024-07-10 13:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("orders", "0003_remove_order_transaction"),
        ("finance", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="order",
            field=models.OneToOneField(
                default="39647851-428f-476c-81ff-9e5b63818d69",
                on_delete=django.db.models.deletion.CASCADE,
                to="orders.order",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="transaction",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
