# Generated by Django 4.2.2 on 2024-08-19 10:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0003_alter_transaction_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="transaction",
            options={"ordering": ("created_at",)},
        ),
    ]
