# Generated by Django 4.2.2 on 2024-08-19 10:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("invite", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invitation",
            name="referral_code",
        ),
    ]
