# Generated by Django 4.2.2 on 2024-08-19 10:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("brands", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="brand",
            options={"ordering": ("created_at",)},
        ),
    ]
