# Generated by Django 4.2.2 on 2024-08-19 10:36

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_user_member_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_image",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="image"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="member_type",
            field=models.CharField(
                choices=[("ST", "Techie"), ("NT", "Non_Techie")], max_length=3
            ),
        ),
    ]
