# Generated by Django 4.2.2 on 2024-09-19 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_member_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='member_type',
            field=models.CharField(choices=[('ST', 'Techie'), ('NT', 'Non_Techie')], max_length=3),
        ),
    ]
