# Generated by Django 4.2.2 on 2024-08-19 10:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0003_alter_inventory_product"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="inventory",
            options={"ordering": ("created_at",), "verbose_name_plural": "inventories"},
        ),
    ]
